[phases.setup]
aptPkgs = [
    "...",
    "wget",
    "unzip",
    "libglib2.0-0",
    "libnss3",
    "libgconf-2-4",
    "libfontconfig1",
    "google-chrome-stable"
]
nixPkgs = ["...", "chromedriver"]
